### ISSUE TITLE
Shortcodes echo instead of return output

### ISSUE THREAD

**Issue by tomjn** [dartiss/draft-concluder#30]
A shortcode should return its output as a string so that it can be displayed in the appropriate place. The two shortcodes in this plugin echo directly instead, so that the shortcode is output when it is processed, not when it is needed. This can break things or cause the shortcode to display in the wrong order ( see nested shortcodes ).

It's easily fixed with output buffers though

**Comment by dartiss** [comment]
Good lord, I can't believe I missed that. I have written so much shortcode code in the past and never done this before. "It's been a while" is my only excuse.

I'll get this fixed.

**Comment by dartiss** [comment]
Fixed. Added to 1.1 release.
