### ISSUE TITLE
Selected function

### ISSUE THREAD

**Issue by tomjn** [dartiss/draft-concluder#31]
I spotted a tonne of if clauses like this:

```php
	echo '<option ';
	if ( 'Daily' == $option ) {
		echo 'selected="selected" ';
	}
	echo 'value="Daily">Daily</option><option ';
```

But WP provides a handy function `selected` to simplify this, so it can be changed to:

```php
	echo '<option ' . selected( 'Daily', $option, false ) . ' value="Daily">Daily</option>';
```

https://developer.wordpress.org/reference/functions/selected/

**Comment by dartiss** [comment]
Good spot, Tom. I've used them before but I copy/pasted from other, older code. I'll correct this in the next iteration.

**Comment by dartiss** [comment]
Closing #20 as a duplicate.

**Comment by dartiss** [comment]
Updated for 1.1
